// generated by tools/gen_manifests.py — do not hand-edit
export const CREDITS = `
<h3>THE NIGHT COUNT</h3>
<div class='billing'>
<p><b>Main Idea</b><br>Thankdapro</p>
<p><b>Plot Writer</b><br>Thankdapro &amp; Claude</p>
<p><b>Coder</b><br>Claude</p>
<p><b>Models</b><br>Built for this game, in Blender<br>
<span class='small'>every model in the station, the lot and the road — except the character rig, which is animation rather than modelling</span></p>
<p><b>Assets</b><br>Freesound &middot; ambientCG &middot; Poly Haven &middot; Quaternius<br>
<span class='small'>sound, surfaces and the rig — every one CC0 or CC-BY, sourced and licence-verified before download; the full list follows</span></p>
</div>
<p>THE NIGHT COUNT is a work of fiction. Meridian Fuel & Provisions, Station 41, Coldbrook and every person and event in the game are invented. Any resemblance to a real company or person is not intended.</p>
<h3>Third-party assets</h3>
<h3>Surfaces, and the models this game was first dressed with — Poly Haven (CC0 1.0)</h3>
<p>Ulan Cabanilla (6), James Ray Cock (6), Yann Kervran (4), Charlotte Baglioni (4), Dimitrios Savva (4), Rob Tuytel (4), MP (3), Jenelle van Heerden (3), PierreB3D (2), Gabriel Radić (2), UM JOORIN (2), Rahul Chaudhary (2), Rico Cilliers (2), Amal Kumar (2), Dario Barresi (2), Joe Seabuhr (1), DaDrood (1), Omar M. El-Safy (1), Ulrich Büch (1), GurJas Studios (1), Benny Weimer (1), Fran Calvente (1), L (1), Slinc (1), Kosan Aziz (1), Mia Pecina Zorko (1), Kuutti Siitonen (1), Niklas (1), Raven van de Werken (1), Alexander Otterbeck (1), Garrison Gager (1), Fabi_G (1), Mutanzom3D (1), Mateusz Sadek (1), Will Evarts (1), Thomas Paul Mouilleron (1), Josh Dean (1), Maximilian Schuster (1), Sean Buckley (1), Jorge Camacho (1), Serhii Khromov (1), Raunox (1), Sergej Majboroda (1), Matterfield (1)</p>
<p>polyhaven.com — released under CC0 1.0. Attribution is not required; it is given here because the work deserves it.</p>
<h3>3D models — poly.pizza</h3>
<p>CC0 1.0:</p>
<div class='small'>qn4grQgHm8 — Quaternius (https://poly.pizza/m/qn4grQgHm8)</div>
<div class='small'>unqqkULtRU — Quaternius (https://poly.pizza/m/unqqkULtRU)</div>
<div class='small'>qqRVRerNSu — iPoly3D (https://poly.pizza/m/qqRVRerNSu)</div>
<div class='small'>IvvdNqXmAW — Quaternius (https://poly.pizza/m/IvvdNqXmAW)</div>
<div class='small'>8sjRm8fnHh — Quaternius (https://poly.pizza/m/8sjRm8fnHh)</div>
<div class='small'>RoCvKBGkoC — Quaternius (https://poly.pizza/m/RoCvKBGkoC)</div>
<div class='small'>eS1OXGo51c — Quaternius (https://poly.pizza/m/eS1OXGo51c)</div>
<div class='small'>cUAsYHDqfD — Quaternius (https://poly.pizza/m/cUAsYHDqfD)</div>
<div class='small'>3revwBHxDC — Quaternius (https://poly.pizza/m/3revwBHxDC)</div>
<div class='small'>VSZubp0ru3 — Quaternius (https://poly.pizza/m/VSZubp0ru3)</div>
<div class='small'>li0YBlBEMz — Quaternius (https://poly.pizza/m/li0YBlBEMz)</div>
<div class='small'>TDgvIuorcX — Quaternius (https://poly.pizza/m/TDgvIuorcX)</div>
<div class='small'>U13zn2LA0w — accidentallyc (https://poly.pizza/m/U13zn2LA0w)</div>
<div class='small'>KOLcdOATw6 — Kenney (https://poly.pizza/m/KOLcdOATw6)</div>
<div class='small'>nFwrlcLvM5 — Quaternius (https://poly.pizza/m/nFwrlcLvM5)</div>
<div class='small'>lAx8JytxGD — Quaternius (https://poly.pizza/m/lAx8JytxGD)</div>
<div class='small'>kGA4N3G7Jv — WilliWam (https://poly.pizza/m/kGA4N3G7Jv)</div>
<div class='small'>cXw6oiFtZ8 — Quaternius (https://poly.pizza/m/cXw6oiFtZ8)</div>
<p>Creative Commons Attribution (CC-BY 3.0) — attribution required and given:</p>
<div class='small'>0ySmwTitJrP — © Poly by Google, licensed CC-BY (https://poly.pizza/m/0ySmwTitJrP)</div>
<div class='small'>EWVe4TaOiB — © J-Toastie, licensed CC-BY (https://poly.pizza/m/EWVe4TaOiB)</div>
<div class='small'>kWobe0q7tf — © J-Toastie, licensed CC-BY (https://poly.pizza/m/kWobe0q7tf)</div>
<div class='small'>a6kuHAjWdYP — © Poly by Google, licensed CC-BY (https://poly.pizza/m/a6kuHAjWdYP)</div>
<div class='small'>dqzY-cxJJsZ — © Poly by Google, licensed CC-BY (https://poly.pizza/m/dqzY-cxJJsZ)</div>
<div class='small'>Tanker Truck — © Alex Safayan, licensed CC-BY (https://poly.pizza/m/3AmDGcCu6Ll)</div>
<div class='small'>4Hazwkymnyg — © Poly by Google, licensed CC-BY (https://poly.pizza/m/4Hazwkymnyg)</div>
<h3>Character rig and animation — Quaternius (CC0 1.0)</h3>
<p>*Universal Animation Library* by Quaternius — quaternius.com — CC0 1.0.</p>
<p>Support the author: patreon.com/quaternius</p>
<h3>Sound — Freesound (CC0 1.0)</h3>
<div class='small'>Aemyn — 1 recording (freesound.org/people/Aemyn/)</div>
<div class='small'>Alex_hears_things — 2 recordings (freesound.org/people/Alex_hears_things/)</div>
<div class='small'>Ali_6868 — 1 recording (freesound.org/people/Ali_6868/)</div>
<div class='small'>ApeinCave — 1 recording (freesound.org/people/ApeinCave/)</div>
<div class='small'>CAT-FOX_ALEX — 1 recording (freesound.org/people/CAT-FOX_ALEX/)</div>
<div class='small'>CVLTIV8R — 1 recording (freesound.org/people/CVLTIV8R/)</div>
<div class='small'>Coral_Island_Studios — 1 recording (freesound.org/people/Coral_Island_Studios/)</div>
<div class='small'>DeVern — 1 recording (freesound.org/people/DeVern/)</div>
<div class='small'>EagleStealthTeam — 1 recording (freesound.org/people/EagleStealthTeam/)</div>
<div class='small'>EricsSoundschmiede — 1 recording (freesound.org/people/EricsSoundschmiede/)</div>
<div class='small'>Exarchik — 1 recording (freesound.org/people/Exarchik/)</div>
<div class='small'>FOSSarts — 1 recording (freesound.org/people/FOSSarts/)</div>
<div class='small'>Fhantum — 1 recording (freesound.org/people/Fhantum/)</div>
<div class='small'>Filmscore — 1 recording (freesound.org/people/Filmscore/)</div>
<div class='small'>FullMetalJedi — 1 recording (freesound.org/people/FullMetalJedi/)</div>
<div class='small'>FunWithSound — 1 recording (freesound.org/people/FunWithSound/)</div>
<div class='small'>GiocoSound — 1 recording (freesound.org/people/GiocoSound/)</div>
<div class='small'>JSilverSound — 1 recording (freesound.org/people/JSilverSound/)</div>
<div class='small'>JohnsonBrandEditing — 1 recording (freesound.org/people/JohnsonBrandEditing/)</div>
<div class='small'>KikeVilaplana — 1 recording (freesound.org/people/KikeVilaplana/)</div>
<div class='small'>LampEight — 1 recording (freesound.org/people/LampEight/)</div>
<div class='small'>Ligidium — 1 recording (freesound.org/people/Ligidium/)</div>
<div class='small'>LukaCafuka — 1 recording (freesound.org/people/LukaCafuka/)</div>
<div class='small'>NickTayloe — 1 recording (freesound.org/people/NickTayloe/)</div>
<div class='small'>NoisyRedFox — 1 recording (freesound.org/people/NoisyRedFox/)</div>
<div class='small'>Nox_Sound — 1 recording (freesound.org/people/Nox_Sound/)</div>
<div class='small'>OwlStorm — 1 recording (freesound.org/people/OwlStorm/)</div>
<div class='small'>P_Chester — 1 recording (freesound.org/people/P_Chester/)</div>
<div class='small'>Profispiesser — 1 recording (freesound.org/people/Profispiesser/)</div>
<div class='small'>RadioCounseling — 1 recording (freesound.org/people/RadioCounseling/)</div>
<div class='small'>ReadeOnly — 1 recording (freesound.org/people/ReadeOnly/)</div>
<div class='small'>RutgerMuller — 1 recording (freesound.org/people/RutgerMuller/)</div>
<div class='small'>Sadiquecat — 1 recording (freesound.org/people/Sadiquecat/)</div>
<div class='small'>Sanderboah — 1 recording (freesound.org/people/Sanderboah/)</div>
<div class='small'>SavReese — 1 recording (freesound.org/people/SavReese/)</div>
<div class='small'>SnowFightStudios — 1 recording (freesound.org/people/SnowFightStudios/)</div>
<div class='small'>SpliceSound — 1 recording (freesound.org/people/SpliceSound/)</div>
<div class='small'>TRP — 1 recording (freesound.org/people/TRP/)</div>
<div class='small'>UberBosser — 1 recording (freesound.org/people/UberBosser/)</div>
<div class='small'>Walter_Odington — 1 recording (freesound.org/people/Walter_Odington/)</div>
<div class='small'>Whats_The_Frequency_Kennett — 1 recording (freesound.org/people/Whats_The_Frequency_Kennett/)</div>
<div class='small'>amthomas101 — 1 recording (freesound.org/people/amthomas101/)</div>
<div class='small'>araneses — 1 recording (freesound.org/people/araneses/)</div>
<div class='small'>awrmacd — 1 recording (freesound.org/people/awrmacd/)</div>
<div class='small'>azumarill — 1 recording (freesound.org/people/azumarill/)</div>
<div class='small'>bajko — 1 recording (freesound.org/people/bajko/)</div>
<div class='small'>bassimat — 2 recordings (freesound.org/people/bassimat/)</div>
<div class='small'>bbrocer — 1 recording (freesound.org/people/bbrocer/)</div>
<div class='small'>bdunis4 — 1 recording (freesound.org/people/bdunis4/)</div>
<div class='small'>burning-mir — 1 recording (freesound.org/people/burning-mir/)</div>
<div class='small'>dhallcomposer — 1 recording (freesound.org/people/dhallcomposer/)</div>
<div class='small'>ecfike — 1 recording (freesound.org/people/ecfike/)</div>
<div class='small'>f-r-a-g-i-l-e — 1 recording (freesound.org/people/f-r-a-g-i-l-e/)</div>
<div class='small'>falcospizaetus — 1 recording (freesound.org/people/falcospizaetus/)</div>
<div class='small'>foad — 1 recording (freesound.org/people/foad/)</div>
<div class='small'>gecop — 1 recording (freesound.org/people/gecop/)</div>
<div class='small'>greatsoundstube — 1 recording (freesound.org/people/greatsoundstube/)</div>
<div class='small'>gtrempe — 1 recording (freesound.org/people/gtrempe/)</div>
<div class='small'>gustavo.hanke — 1 recording (freesound.org/people/gustavo.hanke/)</div>
<div class='small'>handygaber — 1 recording (freesound.org/people/handygaber/)</div>
<div class='small'>itinerantmonk108 — 2 recordings (freesound.org/people/itinerantmonk108/)</div>
<div class='small'>jascha23 — 1 recording (freesound.org/people/jascha23/)</div>
<div class='small'>khenshom — 1 recording (freesound.org/people/khenshom/)</div>
<div class='small'>kkenny101 — 1 recording (freesound.org/people/kkenny101/)</div>
<div class='small'>klau78 — 1 recording (freesound.org/people/klau78/)</div>
<div class='small'>kyles — 13 recordings (freesound.org/people/kyles/)</div>
<div class='small'>leonelmail — 2 recordings (freesound.org/people/leonelmail/)</div>
<div class='small'>lreeve — 1 recording (freesound.org/people/lreeve/)</div>
<div class='small'>magnus1906 — 1 recording (freesound.org/people/magnus1906/)</div>
<div class='small'>memuse — 1 recording (freesound.org/people/memuse/)</div>
<div class='small'>ondrosik — 2 recordings (freesound.org/people/ondrosik/)</div>
<div class='small'>owstu — 1 recording (freesound.org/people/owstu/)</div>
<div class='small'>peridactyloptrix — 1 recording (freesound.org/people/peridactyloptrix/)</div>
<div class='small'>perspektywa_tn — 1 recording (freesound.org/people/perspektywa_tn/)</div>
<div class='small'>pryanic — 1 recording (freesound.org/people/pryanic/)</div>
<div class='small'>qubodup — 1 recording (freesound.org/people/qubodup/)</div>
<div class='small'>ryuuzan — 1 recording (freesound.org/people/ryuuzan/)</div>
<div class='small'>se2001 — 1 recording (freesound.org/people/se2001/)</div>
<div class='small'>szegvari — 1 recording (freesound.org/people/szegvari/)</div>
<div class='small'>the_toilet_guy — 1 recording (freesound.org/people/the_toilet_guy/)</div>
<div class='small'>thebeigee — 1 recording (freesound.org/people/thebeigee/)</div>
<div class='small'>vhio — 1 recording (freesound.org/people/vhio/)</div>
<div class='small'>xUMR — 1 recording (freesound.org/people/xUMR/)</div>
<div class='small'>xkeril — 1 recording (freesound.org/people/xkeril/)</div>
<div class='small'>zerolagtime — 1 recording (freesound.org/people/zerolagtime/)</div>
<div class='small'>zoombackcamera — 1 recording (freesound.org/people/zoombackcamera/)</div>
<p>All sounds are CC0 1.0. Full per-file provenance is in docs/AUDIO_ASSET_MANIFEST.md.</p>
<h3>Engine</h3>
<p>three.js r160 — MIT Licence, © 2010–2024 three.js authors. Bundled in vendor/, licence text at vendor/LICENSE.three.</p>
<h3>Voice</h3>
<p>See docs/VOICE_ASSET_MANIFEST.md. The game contains no text-to-speech, no AI-generated speech and no cloned voices. Every human sound in the build is a recording of a real person, published under CC0.</p>
`;

export const CREDITS_TEXT = `
                      T H E   N I G H T   C O U N T

        Written, designed, built, dressed and tested as one project.

                     Main idea            Thankdapro
                     Plot                 Thankdapro & Claude
                     Code                 Claude
                     Models               built in Blender for this game
                     Sound and surfaces   Freesound, ambientCG, Poly Haven
                     Character rig        Quaternius

THE NIGHT COUNT — ATTRIBUTION

THE NIGHT COUNT is a work of fiction. Meridian Fuel & Provisions,
    Station 41, Coldbrook and every person and event in the game
    are invented. Any resemblance to a real company or person is
    not intended.

THIRD-PARTY ASSETS

SURFACES, AND THE MODELS THIS GAME WAS FIRST DRESSED WITH — POLY
    HAVEN (CC0 1.0)

Ulan Cabanilla (6), James Ray Cock (6), Yann Kervran (4),
    Charlotte Baglioni (4), Dimitrios Savva (4), Rob Tuytel (4),
    MP (3), Jenelle van Heerden (3), PierreB3D (2), Gabriel Radić
    (2), UM JOORIN (2), Rahul Chaudhary (2), Rico Cilliers (2),
    Amal Kumar (2), Dario Barresi (2), Joe Seabuhr (1), DaDrood
    (1), Omar M. El-Safy (1), Ulrich Büch (1), GurJas Studios
    (1), Benny Weimer (1), Fran Calvente (1), L (1), Slinc (1),
    Kosan Aziz (1), Mia Pecina Zorko (1), Kuutti Siitonen (1),
    Niklas (1), Raven van de Werken (1), Alexander Otterbeck (1),
    Garrison Gager (1), Fabi_G (1), Mutanzom3D (1), Mateusz Sadek
    (1), Will Evarts (1), Thomas Paul Mouilleron (1), Josh Dean
    (1), Maximilian Schuster (1), Sean Buckley (1), Jorge Camacho
    (1), Serhii Khromov (1), Raunox (1), Sergej Majboroda (1),
    Matterfield (1)

polyhaven.com — released under CC0 1.0. Attribution is not
    required; it is given here because the work deserves it.

3D MODELS — POLY.PIZZA

CC0 1.0:

  qn4grQgHm8 — Quaternius (https://poly.pizza/m/qn4grQgHm8)
  unqqkULtRU — Quaternius (https://poly.pizza/m/unqqkULtRU)
  qqRVRerNSu — iPoly3D (https://poly.pizza/m/qqRVRerNSu)
  IvvdNqXmAW — Quaternius (https://poly.pizza/m/IvvdNqXmAW)
  8sjRm8fnHh — Quaternius (https://poly.pizza/m/8sjRm8fnHh)
  RoCvKBGkoC — Quaternius (https://poly.pizza/m/RoCvKBGkoC)
  eS1OXGo51c — Quaternius (https://poly.pizza/m/eS1OXGo51c)
  cUAsYHDqfD — Quaternius (https://poly.pizza/m/cUAsYHDqfD)
  3revwBHxDC — Quaternius (https://poly.pizza/m/3revwBHxDC)
  VSZubp0ru3 — Quaternius (https://poly.pizza/m/VSZubp0ru3)
  li0YBlBEMz — Quaternius (https://poly.pizza/m/li0YBlBEMz)
  TDgvIuorcX — Quaternius (https://poly.pizza/m/TDgvIuorcX)
  U13zn2LA0w — accidentallyc (https://poly.pizza/m/U13zn2LA0w)
  KOLcdOATw6 — Kenney (https://poly.pizza/m/KOLcdOATw6)
  nFwrlcLvM5 — Quaternius (https://poly.pizza/m/nFwrlcLvM5)
  lAx8JytxGD — Quaternius (https://poly.pizza/m/lAx8JytxGD)
  kGA4N3G7Jv — WilliWam (https://poly.pizza/m/kGA4N3G7Jv)
  cXw6oiFtZ8 — Quaternius (https://poly.pizza/m/cXw6oiFtZ8)

Creative Commons Attribution (CC-BY 3.0) — attribution required
    and given:

  0ySmwTitJrP — © Poly by Google, licensed CC-BY
    (https://poly.pizza/m/0ySmwTitJrP)
  EWVe4TaOiB — © J-Toastie, licensed CC-BY
    (https://poly.pizza/m/EWVe4TaOiB)
  kWobe0q7tf — © J-Toastie, licensed CC-BY
    (https://poly.pizza/m/kWobe0q7tf)
  a6kuHAjWdYP — © Poly by Google, licensed CC-BY
    (https://poly.pizza/m/a6kuHAjWdYP)
  dqzY-cxJJsZ — © Poly by Google, licensed CC-BY
    (https://poly.pizza/m/dqzY-cxJJsZ)
  Tanker Truck — © Alex Safayan, licensed CC-BY
    (https://poly.pizza/m/3AmDGcCu6Ll)
  4Hazwkymnyg — © Poly by Google, licensed CC-BY
    (https://poly.pizza/m/4Hazwkymnyg)

CHARACTER RIG AND ANIMATION — QUATERNIUS (CC0 1.0)

*Universal Animation Library* by Quaternius — quaternius.com —
    CC0 1.0.
Support the author: patreon.com/quaternius

SOUND — FREESOUND (CC0 1.0)

  Aemyn — 1 recording (freesound.org/people/Aemyn/)
  Alex_hears_things — 2 recordings
    (freesound.org/people/Alex_hears_things/)
  Ali_6868 — 1 recording (freesound.org/people/Ali_6868/)
  ApeinCave — 1 recording (freesound.org/people/ApeinCave/)
  CAT-FOX_ALEX — 1 recording (freesound.org/people/CAT-FOX_ALEX/)
  CVLTIV8R — 1 recording (freesound.org/people/CVLTIV8R/)
  Coral_Island_Studios — 1 recording
    (freesound.org/people/Coral_Island_Studios/)
  DeVern — 1 recording (freesound.org/people/DeVern/)
  EagleStealthTeam — 1 recording
    (freesound.org/people/EagleStealthTeam/)
  EricsSoundschmiede — 1 recording
    (freesound.org/people/EricsSoundschmiede/)
  Exarchik — 1 recording (freesound.org/people/Exarchik/)
  FOSSarts — 1 recording (freesound.org/people/FOSSarts/)
  Fhantum — 1 recording (freesound.org/people/Fhantum/)
  Filmscore — 1 recording (freesound.org/people/Filmscore/)
  FullMetalJedi — 1 recording (freesound.org/people/FullMetalJedi/
    )
  FunWithSound — 1 recording (freesound.org/people/FunWithSound/)
  GiocoSound — 1 recording (freesound.org/people/GiocoSound/)
  JSilverSound — 1 recording (freesound.org/people/JSilverSound/)
  JohnsonBrandEditing — 1 recording
    (freesound.org/people/JohnsonBrandEditing/)
  KikeVilaplana — 1 recording (freesound.org/people/KikeVilaplana/
    )
  LampEight — 1 recording (freesound.org/people/LampEight/)
  Ligidium — 1 recording (freesound.org/people/Ligidium/)
  LukaCafuka — 1 recording (freesound.org/people/LukaCafuka/)
  NickTayloe — 1 recording (freesound.org/people/NickTayloe/)
  NoisyRedFox — 1 recording (freesound.org/people/NoisyRedFox/)
  Nox_Sound — 1 recording (freesound.org/people/Nox_Sound/)
  OwlStorm — 1 recording (freesound.org/people/OwlStorm/)
  P_Chester — 1 recording (freesound.org/people/P_Chester/)
  Profispiesser — 1 recording (freesound.org/people/Profispiesser/
    )
  RadioCounseling — 1 recording
    (freesound.org/people/RadioCounseling/)
  ReadeOnly — 1 recording (freesound.org/people/ReadeOnly/)
  RutgerMuller — 1 recording (freesound.org/people/RutgerMuller/)
  Sadiquecat — 1 recording (freesound.org/people/Sadiquecat/)
  Sanderboah — 1 recording (freesound.org/people/Sanderboah/)
  SavReese — 1 recording (freesound.org/people/SavReese/)
  SnowFightStudios — 1 recording
    (freesound.org/people/SnowFightStudios/)
  SpliceSound — 1 recording (freesound.org/people/SpliceSound/)
  TRP — 1 recording (freesound.org/people/TRP/)
  UberBosser — 1 recording (freesound.org/people/UberBosser/)
  Walter_Odington — 1 recording
    (freesound.org/people/Walter_Odington/)
  Whats_The_Frequency_Kennett — 1 recording
    (freesound.org/people/Whats_The_Frequency_Kennett/)
  amthomas101 — 1 recording (freesound.org/people/amthomas101/)
  araneses — 1 recording (freesound.org/people/araneses/)
  awrmacd — 1 recording (freesound.org/people/awrmacd/)
  azumarill — 1 recording (freesound.org/people/azumarill/)
  bajko — 1 recording (freesound.org/people/bajko/)
  bassimat — 2 recordings (freesound.org/people/bassimat/)
  bbrocer — 1 recording (freesound.org/people/bbrocer/)
  bdunis4 — 1 recording (freesound.org/people/bdunis4/)
  burning-mir — 1 recording (freesound.org/people/burning-mir/)
  dhallcomposer — 1 recording (freesound.org/people/dhallcomposer/
    )
  ecfike — 1 recording (freesound.org/people/ecfike/)
  f-r-a-g-i-l-e — 1 recording (freesound.org/people/f-r-a-g-i-l-e/
    )
  falcospizaetus — 1 recording
    (freesound.org/people/falcospizaetus/)
  foad — 1 recording (freesound.org/people/foad/)
  gecop — 1 recording (freesound.org/people/gecop/)
  greatsoundstube — 1 recording
    (freesound.org/people/greatsoundstube/)
  gtrempe — 1 recording (freesound.org/people/gtrempe/)
  gustavo.hanke — 1 recording (freesound.org/people/gustavo.hanke/
    )
  handygaber — 1 recording (freesound.org/people/handygaber/)
  itinerantmonk108 — 2 recordings
    (freesound.org/people/itinerantmonk108/)
  jascha23 — 1 recording (freesound.org/people/jascha23/)
  khenshom — 1 recording (freesound.org/people/khenshom/)
  kkenny101 — 1 recording (freesound.org/people/kkenny101/)
  klau78 — 1 recording (freesound.org/people/klau78/)
  kyles — 13 recordings (freesound.org/people/kyles/)
  leonelmail — 2 recordings (freesound.org/people/leonelmail/)
  lreeve — 1 recording (freesound.org/people/lreeve/)
  magnus1906 — 1 recording (freesound.org/people/magnus1906/)
  memuse — 1 recording (freesound.org/people/memuse/)
  ondrosik — 2 recordings (freesound.org/people/ondrosik/)
  owstu — 1 recording (freesound.org/people/owstu/)
  peridactyloptrix — 1 recording
    (freesound.org/people/peridactyloptrix/)
  perspektywa_tn — 1 recording
    (freesound.org/people/perspektywa_tn/)
  pryanic — 1 recording (freesound.org/people/pryanic/)
  qubodup — 1 recording (freesound.org/people/qubodup/)
  ryuuzan — 1 recording (freesound.org/people/ryuuzan/)
  se2001 — 1 recording (freesound.org/people/se2001/)
  szegvari — 1 recording (freesound.org/people/szegvari/)
  the_toilet_guy — 1 recording
    (freesound.org/people/the_toilet_guy/)
  thebeigee — 1 recording (freesound.org/people/thebeigee/)
  vhio — 1 recording (freesound.org/people/vhio/)
  xUMR — 1 recording (freesound.org/people/xUMR/)
  xkeril — 1 recording (freesound.org/people/xkeril/)
  zerolagtime — 1 recording (freesound.org/people/zerolagtime/)
  zoombackcamera — 1 recording
    (freesound.org/people/zoombackcamera/)

All sounds are CC0 1.0. Full per-file provenance is in
    docs/AUDIO_ASSET_MANIFEST.md.

ENGINE

three.js r160 — MIT Licence, © 2010–2024 three.js authors.
    Bundled in vendor/, licence text at vendor/LICENSE.three.

VOICE

See docs/VOICE_ASSET_MANIFEST.md. The game contains no
    text-to-speech, no AI-generated speech and no cloned voices.
    Every human sound in the build is a recording of a real
    person, published under CC0.
`;
